
language: cpp

env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "rJyMYSWpKiaco2wLm/eKpRfyaCkWcf1moE4vcSUnckyLP5ORnJS37MSUBsU26b7LXIqkOIb2BwJCn8s1vMUldk3eZub1rZPLVSh4GXIOHsJJ84wDpqBIgu+xsk8NXqXArTi9kbSAAVGlkslrl5pZ77bcLLQ2Nu8oPlXGpKzjEfHXpgZzZLJ4Xv7Vo3cOzKYDBn14oYcKxTsN5Tzny7GLJQpfXE1eRodcTFEL8g0JkA88cIBmaPLyLq9tlzazF8WHG+A3WOz0sikhgIAue59TBLm/sy3hmzjr9185ln+UxRnKTJDagRkBcnp0Wk//t3sxKySBAgPueftOqB5xAvr9U3qs9sfi1cBgJoCACFVh5ghZK00LqgrtxA+XWeisw9NHt4nBQ1FKw3zVg737HfCHuK+wVuC9pnSXWFVXh1aCgNLO69rL+dn0h5hD7LrVpwoc7OaKK6/xlTV4zZ2Xe0pK0HfQBh2CqaVSK9gIuHJIbS9P4E4LtbOCNi259C+3AXfB8+XfixsCVYFE+CMRFE4vaiRFl8FiwhBng5BBMrWPV8lS9nJ0KBq8D0SkbyKnivmRv6hmQ3UYa4PskkMm3jzl0eyLNsslGOEeTOum9l1yhM8WwiZFzJP1QqhxYl/NKuGRpRvPa+88f3/buZyXigFkRAT4/6daYgInCPFJKcS3ERA="

addons:
  coverity_scan:
    project:
      name: "itchio/elevate"
      description: "Command-line privilege elevation on Windows Vista and higher"
    notification_email: fasterthanlime@gmail.com
    build_command: "make"
    branch_pattern: coverity_scan

matrix:
  include:
   - os: linux
     env: ELEVATE_OS=windows ELEVATE_ARCH=386 TRIPLET=i686-w64-mingw32
     addons:
       apt:
         packages:
           - p7zip-full
           - gcc-mingw-w64-i686
           - g++-mingw-w64-i686
           - binutils-mingw-w64-i686
   - os: linux
     env: ELEVATE_OS=windows ELEVATE_ARCH=amd64 TRIPLET=x86_64-w64-mingw32
     addons:
       apt:
         packages:
           - p7zip-full
           - gcc-mingw-w64-x86-64
           - g++-mingw-w64-x86-64
           - binutils-mingw-w64-x86-64
script:
  - if [[ -n $TRAVIS_TAG ]]; then export ELEVATE_CFLAGS="-DELEVATE_VERSION=\\\"$TRAVIS_TAG\\\""; fi
  - make
  - file elevate.exe || true
before_deploy:
  - mkdir -p build
  - cp elevate.exe build/
  - mkdir -p dist
  - (cd dist && 7za a elevate.7z ../build/*)
  - mkdir -p meta
  - echo $TRAVIS_TAG > meta/LATEST
deploy:
  - provider: s3
    access_key_id: AKIAJLM56QAT7VMT756A
    secret_access_key:
      secure: WVOEEPCyi2g+CoboB10eVaCqgVTazsy5tcmuo+rBhuDpeRHjeNduhgsUCtxQdFQlqePD+z9+xWU5bX1LvfmepcYCwz7KdsKQ92soRL3dYa68fI5iMlgT6iyxeCCoekHDUl47KtHGp5w/0p7veBU64K5NzuuMM3deANwosbSzYbdB7WfLTgTNQ5xUALB7vdE5is/HhBy1ngalV6ZGP8p+8s+NS46gdELtLfgChfgSH8jDvmb1gmh1KgvozPgyQ3if4W4inBXVXj0KQ6dYJFMjOFw08YiMrrY017m4XYIHUEhhPR6CbWMtYFGwIlUYE7aUpB59ae1CgnU5FZlIr0bv3LUBJC4HeeOSxPq7H2eK+A2PcdLH5wqhUTE6PlCnDCjE0arMLknCBerXEYz5wznRcxg9SzKk1ORemiAdo2Kn/QGV4xfnZ3QQDw0QfGi5oXYi/jXVEIOIMmst0vM8axBauGOOxRAxknHbavFpOwMsfmHDdjn8IHI9efgGiPIRtE8f0RB2uGHcDoHlqEyvIQ7h9XaAq8AHdUrrypeEoeSka22tyaO84tZuSN9Amxk4YJ9OgZybYFPVZ8U90yJOYExMh5RpNYlxn5V08gIL2M47RLcrJK5cLKoPSfKU7nd5DcLkQ6Z3C743PdGS+hPJOhZcC/Vj2/tYHvxDaEUZFBXil4s=
    bucket: misc.amos.me
    upload-dir: elevate/$ELEVATE_OS-$ELEVATE_ARCH/$TRAVIS_TAG
    local_dir: dist
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: itchio/elevate
  - provider: s3
    access_key_id: AKIAJLM56QAT7VMT756A
    secret_access_key:
      secure: WVOEEPCyi2g+CoboB10eVaCqgVTazsy5tcmuo+rBhuDpeRHjeNduhgsUCtxQdFQlqePD+z9+xWU5bX1LvfmepcYCwz7KdsKQ92soRL3dYa68fI5iMlgT6iyxeCCoekHDUl47KtHGp5w/0p7veBU64K5NzuuMM3deANwosbSzYbdB7WfLTgTNQ5xUALB7vdE5is/HhBy1ngalV6ZGP8p+8s+NS46gdELtLfgChfgSH8jDvmb1gmh1KgvozPgyQ3if4W4inBXVXj0KQ6dYJFMjOFw08YiMrrY017m4XYIHUEhhPR6CbWMtYFGwIlUYE7aUpB59ae1CgnU5FZlIr0bv3LUBJC4HeeOSxPq7H2eK+A2PcdLH5wqhUTE6PlCnDCjE0arMLknCBerXEYz5wznRcxg9SzKk1ORemiAdo2Kn/QGV4xfnZ3QQDw0QfGi5oXYi/jXVEIOIMmst0vM8axBauGOOxRAxknHbavFpOwMsfmHDdjn8IHI9efgGiPIRtE8f0RB2uGHcDoHlqEyvIQ7h9XaAq8AHdUrrypeEoeSka22tyaO84tZuSN9Amxk4YJ9OgZybYFPVZ8U90yJOYExMh5RpNYlxn5V08gIL2M47RLcrJK5cLKoPSfKU7nd5DcLkQ6Z3C743PdGS+hPJOhZcC/Vj2/tYHvxDaEUZFBXil4s=
    bucket: misc.amos.me
    upload-dir: elevate/$ELEVATE_OS-$ELEVATE_ARCH
    local_dir: meta
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: itchio/elevate
