
language: c

env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "rJyMYSWpKiaco2wLm/eKpRfyaCkWcf1moE4vcSUnckyLP5ORnJS37MSUBsU26b7LXIqkOIb2BwJCn8s1vMUldk3eZub1rZPLVSh4GXIOHsJJ84wDpqBIgu+xsk8NXqXArTi9kbSAAVGlkslrl5pZ77bcLLQ2Nu8oPlXGpKzjEfHXpgZzZLJ4Xv7Vo3cOzKYDBn14oYcKxTsN5Tzny7GLJQpfXE1eRodcTFEL8g0JkA88cIBmaPLyLq9tlzazF8WHG+A3WOz0sikhgIAue59TBLm/sy3hmzjr9185ln+UxRnKTJDagRkBcnp0Wk//t3sxKySBAgPueftOqB5xAvr9U3qs9sfi1cBgJoCACFVh5ghZK00LqgrtxA+XWeisw9NHt4nBQ1FKw3zVg737HfCHuK+wVuC9pnSXWFVXh1aCgNLO69rL+dn0h5hD7LrVpwoc7OaKK6/xlTV4zZ2Xe0pK0HfQBh2CqaVSK9gIuHJIbS9P4E4LtbOCNi259C+3AXfB8+XfixsCVYFE+CMRFE4vaiRFl8FiwhBng5BBMrWPV8lS9nJ0KBq8D0SkbyKnivmRv6hmQ3UYa4PskkMm3jzl0eyLNsslGOEeTOum9l1yhM8WwiZFzJP1QqhxYl/NKuGRpRvPa+88f3/buZyXigFkRAT4/6daYgInCPFJKcS3ERA="

matrix:
  include:
   - os: linux
     env: ELEVATE_OS=windows ELEVATE_ARCH=386 TRIPLET=i686-w64-mingw32
     addons:
       apt:
         packages:
           - p7zip-full
           - gcc-mingw-w64-i686
           - g++-mingw-w64-i686
           - binutils-mingw-w64-i686
         coverity_scan:
           project:
             name: "itchio/elevate"
             description: "Build submitted via Travis CI"
           notification_email: fasterthanlime@gmail.com
           build_command_prepend: ""
           build_command: "make"
           branch_pattern: coverity_scan
   - os: linux
     env: ELEVATE_OS=windows ELEVATE_ARCH=amd64 TRIPLET=x86_64-w64-mingw32
     addons:
       apt:
         packages:
           - p7zip-full
           - gcc-mingw-w64-x86-64
           - g++-mingw-w64-x86-64
           - binutils-mingw-w64-x86-64
         coverity_scan:
           project:
             name: "itchio/elevate"
             description: "Build submitted via Travis CI"
           notification_email: fasterthanlime@gmail.com
           build_command_prepend: ""
           build_command: "make"
           branch_pattern: coverity_scan
script:
  - if [[ -n $TRAVIS_TAG ]]; then export ELEVATE_CFLAGS="-DELEVATE_VERSION=\\\"$TRAVIS_TAG\\\""; fi
  - make
  - file elevate.exe || true
before_deploy:
  - mkdir -p build
  - cp elevate.exe build/
  - mkdir -p dist
  - (cd dist && 7za a elevate.7z ../build/*)
  - mkdir -p meta
  - echo $TRAVIS_TAG > meta/LATEST
deploy:
  - provider: s3
    access_key_id: AKIAJC6IFO2T5RCEHRGA
    secret_access_key:
      secure: ajjDMCL07v8pdti4j7KP0XWR/Jnld/7igKlW52AlBovqj5z2xOjY8kqSylu/gTdP1XRtDzoSQrH8ZLCT4v1eGr+QWxcIiWcNKbpkCY9nkc8S0Ovdr1poUrx9wDQUU7V351Pd7+nUGjM3ZPuvBOTJxlGcr2x4pdL1ad6CmJ+NyZlY2+uNJ5r1o/OS5iqF9RMasbT9Tlr4xkcPPxCdWZ/Bn6tIiwpxSOZ9cFo1cyihC5QaWP0lB9uNdL57MWkSRH0jYGRaBmj7pol09C/GUVM0AjNbJNb04J+UG2dK3etLgvkIRZSxo8tXjBEZcCP3Uq8RJ3zCha76b38aCOPo7iylf1CfHko73EaHXRg+ShH9SThq2BSvD8hwsLEX4xe31WtRWKAH3qSXeubpYDuNfqrB1TBqO6dVy7A5aoiQdMob7Styqca+IwaDgPIRzY743oUk4S8ZFMpZgEbswaUtPVy/TOxqionBInPuFNRhb0mnLijc0p/EeXZsVfcwH4OcXaRCKSNkR9SYTmZqPeevCZ1069XR1/chRWukKieMbtCIFpubngXs+XhUfd3qXUStqOcdf0GMM5QrLv0a7Fqhim3jKQw+uTVOgvXaTIT6YpLG4+TblmAMyc/CYkCtxSLgUy9dPZ6Df4v87xh3JUjCB2l0PYZzJHQ5QtnVSuoWpNv3O8o=
    bucket: misc.amos.me
    upload-dir: elevate/$ELEVATE_OS-$ELEVATE_ARCH/$TRAVIS_TAG
    local_dir: dist
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: itchio/elevate
  - provider: s3
    access_key_id: AKIAJC6IFO2T5RCEHRGA
    secret_access_key:
      secure: ajjDMCL07v8pdti4j7KP0XWR/Jnld/7igKlW52AlBovqj5z2xOjY8kqSylu/gTdP1XRtDzoSQrH8ZLCT4v1eGr+QWxcIiWcNKbpkCY9nkc8S0Ovdr1poUrx9wDQUU7V351Pd7+nUGjM3ZPuvBOTJxlGcr2x4pdL1ad6CmJ+NyZlY2+uNJ5r1o/OS5iqF9RMasbT9Tlr4xkcPPxCdWZ/Bn6tIiwpxSOZ9cFo1cyihC5QaWP0lB9uNdL57MWkSRH0jYGRaBmj7pol09C/GUVM0AjNbJNb04J+UG2dK3etLgvkIRZSxo8tXjBEZcCP3Uq8RJ3zCha76b38aCOPo7iylf1CfHko73EaHXRg+ShH9SThq2BSvD8hwsLEX4xe31WtRWKAH3qSXeubpYDuNfqrB1TBqO6dVy7A5aoiQdMob7Styqca+IwaDgPIRzY743oUk4S8ZFMpZgEbswaUtPVy/TOxqionBInPuFNRhb0mnLijc0p/EeXZsVfcwH4OcXaRCKSNkR9SYTmZqPeevCZ1069XR1/chRWukKieMbtCIFpubngXs+XhUfd3qXUStqOcdf0GMM5QrLv0a7Fqhim3jKQw+uTVOgvXaTIT6YpLG4+TblmAMyc/CYkCtxSLgUy9dPZ6Df4v87xh3JUjCB2l0PYZzJHQ5QtnVSuoWpNv3O8o=
    bucket: misc.amos.me
    upload-dir: elevate/$ELEVATE_OS-$ELEVATE_ARCH
    local_dir: meta
    acl: public_read
    skip_cleanup: true
    on:
      tags: true
      repo: itchio/elevate
